[package]
name = "jn-actix-initializer-macros"
version = "0.1.0"
authors = ["John Robert <johnr.delacruz0102@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
regex = "1"
